#StackName: CUSTOMERNAME-ENVIRONMENT-RESOURCENAME
#StackName: ROUTETABLE-TDB-PRD-IN-01
#
# 2019/09/04 / tkkosak@amazon.com
#
Resources:
  rtbforcommon:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue vpcsandboxdi
      Tags:
        - Key: Name
          Value: rtb-common
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common

  routeforcommon:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforcommon
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayId: tgw-05c01e2dfff18b2e1

  subnetassocforcommon1a:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforcommon
      SubnetId: !ImportValue subnetcommon1a96

  subnetassocforcommon1c:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforcommon
      SubnetId: !ImportValue subnetcommon1c128

  subnetassocforcommon1d:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforcommon
      SubnetId: !ImportValue subnetcommon1d160

  rtbforprivate:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue vpcsandboxdi
      Tags:
        - Key: Name
          Value: rtb-private
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common

  routeforprivate01:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforprivate
      DestinationCidrBlock: 172.29.0.0/16
      TransitGatewayId: tgw-05c01e2dfff18b2e1

  routeforprivate02:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforprivate
      DestinationCidrBlock: 10.0.0.0/8
      TransitGatewayId: tgw-05c01e2dfff18b2e1

  routeforprivate03:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforprivate
      DestinationCidrBlock: 172.16.0.0/12
      TransitGatewayId: tgw-05c01e2dfff18b2e1

  subnetassocforprivate1a:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforprivate
      SubnetId: !ImportValue subnetprivate1a0

  subnetassocforprivate1c:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforprivate
      SubnetId: !ImportValue subnetprivate1c32

  subnetassocforprivate1d:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforprivate
      SubnetId: !ImportValue subnetprivate1d64

  rtbforprotect:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue vpcsandboxdi
      Tags:
        - Key: Name
          Value: rtb-protect
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common

  routeforprotect01:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforprotect
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayId: tgw-05c01e2dfff18b2e1

  subnetassocforprotect1a:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforprotect
      SubnetId: !ImportValue subnetprotect1a0

  subnetassocforprotect1c:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforprotect
      SubnetId: !ImportValue subnetprotect1c128

  s3endpointsandboxdi01:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      ServiceName: "com.amazonaws.ap-northeast-1.s3"
      RouteTableIds:
        - !Ref rtbforprotect
        - !Ref rtbforprivate
      VpcId: !ImportValue vpcsandboxdi

Outputs:
  s3endpointsandboxdi01:
    Description: S3 Endpoint for Sandbox / Development / Internal
    Value: !Ref s3endpointsandboxdi01
    Export:
      Name: s3endpointsandboxdi01

  rtbforcommon:
    Description: Common RouteTable for Sandbox / Development / Internal
    Value: !Ref rtbforcommon
    Export:
      Name: rtbforcommon

  rtbforprivate:
    Description: Private RouteTable for Sandbox / Development / Internal
    Value: !Ref rtbforprivate
    Export:
      Name: rtbforprivate

  rtbforprotect:
    Description: Protect RouteTable for Sandbox / Development / Internal
    Value: !Ref rtbforprotect
    Export:
      Name: rtbforprotect
