#StackName: CUSTOMERNAME-Env-RESOURCENAME
#StackName: network01-sandbox-d-I
#
# 2020/12/24 / tkkosak@amazon.com
#
Resources:
  vpcsandboxdi:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 172.29.134.0/23
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: vpc-sandbox-d-i
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common

  subnetprotect1a0:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: 172.29.134.0/25
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: subnet-protect-1a-0
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common
      VpcId: !Ref vpcsandboxdi

  subnetprotect1c128:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      CidrBlock: 172.29.134.128/25
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: subnet-protect-1c-128
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common
      VpcId: !Ref vpcsandboxdi

  subnetprivate1a0:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: 172.29.135.0/27
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: subnet-private-1a-0
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common
      VpcId: !Ref vpcsandboxdi

  subnetprivate1c32:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      CidrBlock: 172.29.135.32/27
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: subnet-private-1c-32
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common
      VpcId: !Ref vpcsandboxdi

  subnetprivate1d64:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1d"
      CidrBlock: 172.29.135.64/27
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: subnet-private-1d-64
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common
      VpcId: !Ref vpcsandboxdi

  subnetcommon1a96:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: 172.29.135.96/27
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: subnet-common-1a-96
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common
      VpcId: !Ref vpcsandboxdi

  subnetcommon1c128:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      CidrBlock: 172.29.135.128/27
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: subnet-common-1c-128
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common
      VpcId: !Ref vpcsandboxdi

  subnetcommon1d160:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1d"
      CidrBlock: 172.29.135.160/27
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: subnet-common-1d-160
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common
      VpcId: !Ref vpcsandboxdi

  attsandboxdi:
    Type: 'AWS::EC2::TransitGatewayAttachment'
    Properties: 
      SubnetIds: 
        - !Ref subnetcommon1a96
        - !Ref subnetcommon1c128
        - !Ref subnetcommon1d160
      Tags:
        - Key: Name
          Value: att-sandbox-d-i
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common
      TransitGatewayId: 'tgw-05c01e2dfff18b2e1'
      VpcId: !Ref vpcsandboxdi

Outputs:
  vpcsandboxdi:
    Description: Sandbox / Development / Internal
    Value: !Ref vpcsandboxdi
    Export:
      Name: vpcsandboxdi

  subnetprotect1a0:
    Description: Subnet for Sandbox / Development / Internal(172.29.134.0/25 Protect-a-0)
    Value: !Ref subnetprotect1a0
    Export:
      Name: subnetprotect1a0

  subnetprotect1c128:
    Description: Subnet for Sandbox / Development / Internal(172.29.134.128/25 Protect-c-128)
    Value: !Ref subnetprotect1c128
    Export:
      Name: subnetprotect1c128

  subnetprivate1a0:
    Description: Subnet for Sandbox / Development / Internal(172.29.135.0/27 Private-a-0)
    Value: !Ref subnetprivate1a0
    Export:
      Name: subnetprivate1a0

  subnetprivate1c32:
    Description: Subnet for Sandbox / Development / Internal(172.29.135.32/27 Private-c-32)
    Value: !Ref subnetprivate1c32
    Export:
      Name: subnetprivate1c32

  subnetprivate1d64:
    Description: Subnet for Sandbox / Development / Internal(172.29.135.64/27 Private-d-64)
    Value: !Ref subnetprivate1d64
    Export:
      Name: subnetprivate1d64

  subnetcommon1a96:
    Description: Subnet for Sandbox / Development / Internal(172.29.135.96/27 Common-a-96)
    Value: !Ref subnetcommon1a96
    Export:
      Name: subnetcommon1a96

  subnetcommon1c128:
    Description: Subnet for Sandbox / Development / Internal(172.29.135.128/27 Common-c-128)
    Value: !Ref subnetcommon1c128
    Export:
      Name: subnetcommon1c128

  subnetcommon1d160:
    Description: Subnet for Sandbox / Development / Internal(172.29.135.160/27 Common-d-160)
    Value: !Ref subnetcommon1d160
    Export:
      Name: subnetcommon1d160

  attsandboxdi:
    Description: TGW Attachment for Sandbox / Development / Internal
    Value: !Ref attsandboxdi
    Export:
      Name: attsandboxdi
