#StackName: CUSTOMERNAME-ENVIRONMENT-RESOURCENAME
#StackName: network02-sandbox-d-E
#
# 2020/12/24 / tkkosak@amazon.com
#
Resources:
  rtbforpublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue vpcsandboxde
      Tags:
        - Key: Name
          Value: rtb-public
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common

  routeforpublic01:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforpublic
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !ImportValue igwsandboxde

  subnetassocforpublic1a:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforpublic
      SubnetId: !ImportValue subnetpublic1a0

  subnetassocforpublic1c:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforpublic
      SubnetId: !ImportValue subnetpublic1c32

  rtbforcommon:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue vpcsandboxde
      Tags:
        - Key: Name
          Value: rtb-common
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common

  routeforcommon:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforcommon
      DestinationCidrBlock: 0.0.0.0/0
      TransitGatewayId: tgw-05c01e2dfff18b2e1

  subnetassocforcommon1a:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforcommon
      SubnetId: !ImportValue subnetcommon1a160

  subnetassocforcommon1c:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforcommon
      SubnetId: !ImportValue subnetcommon1c192

  subnetassocforcommon1d:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforcommon
      SubnetId: !ImportValue subnetcommon1d224

  rtbforprivate:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue vpcsandboxde
      Tags:
        - Key: Name
          Value: rtb-private
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common

  routeforprivate01:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforprivate
      DestinationCidrBlock: 172.29.132.0/23
      TransitGatewayId: tgw-05c01e2dfff18b2e1

  routeforprivate02:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforprivate
      DestinationCidrBlock: 172.29.128.160/27
      TransitGatewayId: tgw-05c01e2dfff18b2e1

  routeforprivate03:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforprivate
      DestinationCidrBlock: 172.29.128.192/27
      TransitGatewayId: tgw-05c01e2dfff18b2e1

  subnetassocforprivate1a:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforprivate
      SubnetId: !ImportValue subnetprivate1a64

  subnetassocforprivate1c:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforprivate
      SubnetId: !ImportValue subnetprivate1c96

  subnetassocforprivate1d:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforprivate
      SubnetId: !ImportValue subnetprivate1d128

  rtbforprotect01:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue vpcsandboxde
      Tags:
        - Key: Name
          Value: rtb-protect-a
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common

  routeforprotect0101:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforprotect01
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !ImportValue ngwsandboxde1a

  routeforprotect0102:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforprotect01
      DestinationCidrBlock: 172.29.132.0/23
      TransitGatewayId: tgw-05c01e2dfff18b2e1

  routeforprotect0103:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforprotect01
      DestinationCidrBlock: 172.29.128.160/27
      TransitGatewayId: tgw-05c01e2dfff18b2e1

  routeforprotect0104:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforprotect01
      DestinationCidrBlock: 172.29.128.192/27
      TransitGatewayId: tgw-05c01e2dfff18b2e1

  subnetassocforprotect1a:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforprotect01
      SubnetId: !ImportValue subnetprotect1a0

  rtbforprotect02:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue vpcsandboxde
      Tags:
        - Key: Name
          Value: rtb-protect-c
        - Key: Owner
          Value: EBR-C340
        - Key: System
          Value: Common

  routeforprotect0201:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforprotect02
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !ImportValue ngwsandboxde1c

  routeforprotect0202:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforprotect02
      DestinationCidrBlock: 172.29.132.0/23
      TransitGatewayId: tgw-05c01e2dfff18b2e1

  routeforprotect0203:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforprotect02
      DestinationCidrBlock: 172.29.128.160/27
      TransitGatewayId: tgw-05c01e2dfff18b2e1

  routeforprotect0204:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbforprotect02
      DestinationCidrBlock: 172.29.128.192/27
      TransitGatewayId: tgw-05c01e2dfff18b2e1

  subnetassocforprotect1c:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref rtbforprotect02
      SubnetId: !ImportValue subnetprotect1c128

  s3endpointsandboxde01:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      ServiceName: "com.amazonaws.ap-northeast-1.s3"
      RouteTableIds:
        - !Ref rtbforprotect01
        - !Ref rtbforprotect02
        - !Ref rtbforprivate
      VpcId: !ImportValue vpcsandboxde

Outputs:
  s3endpointsandboxde01:
    Description: S3 Endpoint for Sandbox / Development / Extermal
    Value: !Ref s3endpointsandboxde01
    Export:
      Name: s3endpointsandboxde01

  rtbforpublic:
    Description: Public RouteTable for Sandbox / Development / Extermal
    Value: !Ref rtbforpublic
    Export:
      Name: rtbforpublic

  rtbforcommon:
    Description: Common RouteTable for Sandbox / Development / Extermal
    Value: !Ref rtbforcommon
    Export:
      Name: rtbforcommon

  rtbforprotect01:
    Description: Protect RouteTable AzA for Sandbox / Development / Extermal
    Value: !Ref rtbforprotect01
    Export:
      Name: rtbforprotect01

  rtbforprotect02:
    Description: Protect RouteTable AzC for Sandbox / Development / Extermal
    Value: !Ref rtbforprotect02
    Export:
      Name: rtbforprotect02

  rtbforprivate:
    Description: Private RouteTable for Sandbox / Development / Extermal
    Value: !Ref rtbforprivate
    Export:
      Name: rtbforprivate
